/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiOliverChatRouteImport } from './routes/api/oliver-chat'
import { Route as AuthenticatedOperacaoRouteImport } from './routes/_authenticated/operacao'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedFerramentasRouteImport } from './routes/_authenticated/ferramentas'
import { Route as AuthenticatedEndossosRouteImport } from './routes/_authenticated/endossos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedApolicesIndexRouteImport } from './routes/_authenticated/apolices.index'
import { Route as ApiPublicPolicySyncCallbackRouteImport } from './routes/api/public/policy-sync-callback'
import { Route as ApiPublicCalendarRemindersTickRouteImport } from './routes/api/public/calendar-reminders-tick'
import { Route as ApiPublicAuditCallbackRouteImport } from './routes/api/public/audit-callback'
import { Route as AuthenticatedFerramentasCalendarioRouteImport } from './routes/_authenticated/ferramentas.calendario'
import { Route as AuthenticatedApolicesIdIndexRouteImport } from './routes/_authenticated/apolices.$id.index'
import { Route as ApiPublicHooksPolicySyncRouteImport } from './routes/api/public/hooks/policy-sync'
import { Route as AuthenticatedApolicesIdEndossosNumRouteImport } from './routes/_authenticated/apolices.$id.endossos.$num'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiOliverChatRoute = ApiOliverChatRouteImport.update({
  id: '/api/oliver-chat',
  path: '/api/oliver-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperacaoRoute = AuthenticatedOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFerramentasRoute =
  AuthenticatedFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEndossosRoute = AuthenticatedEndossosRouteImport.update({
  id: '/endossos',
  path: '/endossos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApolicesIndexRoute =
  AuthenticatedApolicesIndexRouteImport.update({
    id: '/apolices/',
    path: '/apolices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPolicySyncCallbackRoute =
  ApiPublicPolicySyncCallbackRouteImport.update({
    id: '/api/public/policy-sync-callback',
    path: '/api/public/policy-sync-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarRemindersTickRoute =
  ApiPublicCalendarRemindersTickRouteImport.update({
    id: '/api/public/calendar-reminders-tick',
    path: '/api/public/calendar-reminders-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuditCallbackRoute = ApiPublicAuditCallbackRouteImport.update({
  id: '/api/public/audit-callback',
  path: '/api/public/audit-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFerramentasCalendarioRoute =
  AuthenticatedFerramentasCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedFerramentasRoute,
  } as any)
const AuthenticatedApolicesIdIndexRoute =
  AuthenticatedApolicesIdIndexRouteImport.update({
    id: '/apolices/$id/',
    path: '/apolices/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPolicySyncRoute =
  ApiPublicHooksPolicySyncRouteImport.update({
    id: '/api/public/hooks/policy-sync',
    path: '/api/public/hooks/policy-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedApolicesIdEndossosNumRoute =
  AuthenticatedApolicesIdEndossosNumRouteImport.update({
    id: '/apolices/$id/endossos/$num',
    path: '/apolices/$id/endossos/$num',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/endossos': typeof AuthenticatedEndossosRoute
  '/ferramentas': typeof AuthenticatedFerramentasRouteWithChildren
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/api/oliver-chat': typeof ApiOliverChatRoute
  '/ferramentas/calendario': typeof AuthenticatedFerramentasCalendarioRoute
  '/api/public/audit-callback': typeof ApiPublicAuditCallbackRoute
  '/api/public/calendar-reminders-tick': typeof ApiPublicCalendarRemindersTickRoute
  '/api/public/policy-sync-callback': typeof ApiPublicPolicySyncCallbackRoute
  '/apolices/': typeof AuthenticatedApolicesIndexRoute
  '/api/public/hooks/policy-sync': typeof ApiPublicHooksPolicySyncRoute
  '/apolices/$id/': typeof AuthenticatedApolicesIdIndexRoute
  '/apolices/$id/endossos/$num': typeof AuthenticatedApolicesIdEndossosNumRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/endossos': typeof AuthenticatedEndossosRoute
  '/ferramentas': typeof AuthenticatedFerramentasRouteWithChildren
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/api/oliver-chat': typeof ApiOliverChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/ferramentas/calendario': typeof AuthenticatedFerramentasCalendarioRoute
  '/api/public/audit-callback': typeof ApiPublicAuditCallbackRoute
  '/api/public/calendar-reminders-tick': typeof ApiPublicCalendarRemindersTickRoute
  '/api/public/policy-sync-callback': typeof ApiPublicPolicySyncCallbackRoute
  '/apolices': typeof AuthenticatedApolicesIndexRoute
  '/api/public/hooks/policy-sync': typeof ApiPublicHooksPolicySyncRoute
  '/apolices/$id': typeof AuthenticatedApolicesIdIndexRoute
  '/apolices/$id/endossos/$num': typeof AuthenticatedApolicesIdEndossosNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/endossos': typeof AuthenticatedEndossosRoute
  '/_authenticated/ferramentas': typeof AuthenticatedFerramentasRouteWithChildren
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/operacao': typeof AuthenticatedOperacaoRoute
  '/api/oliver-chat': typeof ApiOliverChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ferramentas/calendario': typeof AuthenticatedFerramentasCalendarioRoute
  '/api/public/audit-callback': typeof ApiPublicAuditCallbackRoute
  '/api/public/calendar-reminders-tick': typeof ApiPublicCalendarRemindersTickRoute
  '/api/public/policy-sync-callback': typeof ApiPublicPolicySyncCallbackRoute
  '/_authenticated/apolices/': typeof AuthenticatedApolicesIndexRoute
  '/api/public/hooks/policy-sync': typeof ApiPublicHooksPolicySyncRoute
  '/_authenticated/apolices/$id/': typeof AuthenticatedApolicesIdIndexRoute
  '/_authenticated/apolices/$id/endossos/$num': typeof AuthenticatedApolicesIdEndossosNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alertas'
    | '/analytics'
    | '/configuracoes'
    | '/endossos'
    | '/ferramentas'
    | '/intelligence'
    | '/operacao'
    | '/api/oliver-chat'
    | '/ferramentas/calendario'
    | '/api/public/audit-callback'
    | '/api/public/calendar-reminders-tick'
    | '/api/public/policy-sync-callback'
    | '/apolices/'
    | '/api/public/hooks/policy-sync'
    | '/apolices/$id/'
    | '/apolices/$id/endossos/$num'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alertas'
    | '/analytics'
    | '/configuracoes'
    | '/endossos'
    | '/ferramentas'
    | '/intelligence'
    | '/operacao'
    | '/api/oliver-chat'
    | '/'
    | '/ferramentas/calendario'
    | '/api/public/audit-callback'
    | '/api/public/calendar-reminders-tick'
    | '/api/public/policy-sync-callback'
    | '/apolices'
    | '/api/public/hooks/policy-sync'
    | '/apolices/$id'
    | '/apolices/$id/endossos/$num'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alertas'
    | '/_authenticated/analytics'
    | '/_authenticated/configuracoes'
    | '/_authenticated/endossos'
    | '/_authenticated/ferramentas'
    | '/_authenticated/intelligence'
    | '/_authenticated/operacao'
    | '/api/oliver-chat'
    | '/_authenticated/'
    | '/_authenticated/ferramentas/calendario'
    | '/api/public/audit-callback'
    | '/api/public/calendar-reminders-tick'
    | '/api/public/policy-sync-callback'
    | '/_authenticated/apolices/'
    | '/api/public/hooks/policy-sync'
    | '/_authenticated/apolices/$id/'
    | '/_authenticated/apolices/$id/endossos/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiOliverChatRoute: typeof ApiOliverChatRoute
  ApiPublicAuditCallbackRoute: typeof ApiPublicAuditCallbackRoute
  ApiPublicCalendarRemindersTickRoute: typeof ApiPublicCalendarRemindersTickRoute
  ApiPublicPolicySyncCallbackRoute: typeof ApiPublicPolicySyncCallbackRoute
  ApiPublicHooksPolicySyncRoute: typeof ApiPublicHooksPolicySyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/oliver-chat': {
      id: '/api/oliver-chat'
      path: '/api/oliver-chat'
      fullPath: '/api/oliver-chat'
      preLoaderRoute: typeof ApiOliverChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operacao': {
      id: '/_authenticated/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof AuthenticatedOperacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas': {
      id: '/_authenticated/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthenticatedFerramentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/endossos': {
      id: '/_authenticated/endossos'
      path: '/endossos'
      fullPath: '/endossos'
      preLoaderRoute: typeof AuthenticatedEndossosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apolices/': {
      id: '/_authenticated/apolices/'
      path: '/apolices'
      fullPath: '/apolices/'
      preLoaderRoute: typeof AuthenticatedApolicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/policy-sync-callback': {
      id: '/api/public/policy-sync-callback'
      path: '/api/public/policy-sync-callback'
      fullPath: '/api/public/policy-sync-callback'
      preLoaderRoute: typeof ApiPublicPolicySyncCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar-reminders-tick': {
      id: '/api/public/calendar-reminders-tick'
      path: '/api/public/calendar-reminders-tick'
      fullPath: '/api/public/calendar-reminders-tick'
      preLoaderRoute: typeof ApiPublicCalendarRemindersTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit-callback': {
      id: '/api/public/audit-callback'
      path: '/api/public/audit-callback'
      fullPath: '/api/public/audit-callback'
      preLoaderRoute: typeof ApiPublicAuditCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ferramentas/calendario': {
      id: '/_authenticated/ferramentas/calendario'
      path: '/calendario'
      fullPath: '/ferramentas/calendario'
      preLoaderRoute: typeof AuthenticatedFerramentasCalendarioRouteImport
      parentRoute: typeof AuthenticatedFerramentasRoute
    }
    '/_authenticated/apolices/$id/': {
      id: '/_authenticated/apolices/$id/'
      path: '/apolices/$id'
      fullPath: '/apolices/$id/'
      preLoaderRoute: typeof AuthenticatedApolicesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/policy-sync': {
      id: '/api/public/hooks/policy-sync'
      path: '/api/public/hooks/policy-sync'
      fullPath: '/api/public/hooks/policy-sync'
      preLoaderRoute: typeof ApiPublicHooksPolicySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apolices/$id/endossos/$num': {
      id: '/_authenticated/apolices/$id/endossos/$num'
      path: '/apolices/$id/endossos/$num'
      fullPath: '/apolices/$id/endossos/$num'
      preLoaderRoute: typeof AuthenticatedApolicesIdEndossosNumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFerramentasRouteChildren {
  AuthenticatedFerramentasCalendarioRoute: typeof AuthenticatedFerramentasCalendarioRoute
}

const AuthenticatedFerramentasRouteChildren: AuthenticatedFerramentasRouteChildren =
  {
    AuthenticatedFerramentasCalendarioRoute:
      AuthenticatedFerramentasCalendarioRoute,
  }

const AuthenticatedFerramentasRouteWithChildren =
  AuthenticatedFerramentasRoute._addFileChildren(
    AuthenticatedFerramentasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEndossosRoute: typeof AuthenticatedEndossosRoute
  AuthenticatedFerramentasRoute: typeof AuthenticatedFerramentasRouteWithChildren
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedOperacaoRoute: typeof AuthenticatedOperacaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApolicesIndexRoute: typeof AuthenticatedApolicesIndexRoute
  AuthenticatedApolicesIdIndexRoute: typeof AuthenticatedApolicesIdIndexRoute
  AuthenticatedApolicesIdEndossosNumRoute: typeof AuthenticatedApolicesIdEndossosNumRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEndossosRoute: AuthenticatedEndossosRoute,
  AuthenticatedFerramentasRoute: AuthenticatedFerramentasRouteWithChildren,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedOperacaoRoute: AuthenticatedOperacaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApolicesIndexRoute: AuthenticatedApolicesIndexRoute,
  AuthenticatedApolicesIdIndexRoute: AuthenticatedApolicesIdIndexRoute,
  AuthenticatedApolicesIdEndossosNumRoute:
    AuthenticatedApolicesIdEndossosNumRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiOliverChatRoute: ApiOliverChatRoute,
  ApiPublicAuditCallbackRoute: ApiPublicAuditCallbackRoute,
  ApiPublicCalendarRemindersTickRoute: ApiPublicCalendarRemindersTickRoute,
  ApiPublicPolicySyncCallbackRoute: ApiPublicPolicySyncCallbackRoute,
  ApiPublicHooksPolicySyncRoute: ApiPublicHooksPolicySyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
