/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as EndossosRouteImport } from './routes/endossos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApolicesIndexRouteImport } from './routes/apolices.index'
import { Route as ApolicesIdRouteImport } from './routes/apolices.$id'
import { Route as ApiPublicPolicySyncCallbackRouteImport } from './routes/api/public/policy-sync-callback'
import { Route as ApiPublicAuditCallbackRouteImport } from './routes/api/public/audit-callback'
import { Route as ApolicesIdEndossosNumRouteImport } from './routes/apolices.$id.endossos.$num'
import { Route as ApiPublicHooksPolicySyncRouteImport } from './routes/api/public/hooks/policy-sync'

const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const EndossosRoute = EndossosRouteImport.update({
  id: '/endossos',
  path: '/endossos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApolicesIndexRoute = ApolicesIndexRouteImport.update({
  id: '/apolices/',
  path: '/apolices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApolicesIdRoute = ApolicesIdRouteImport.update({
  id: '/apolices/$id',
  path: '/apolices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPolicySyncCallbackRoute =
  ApiPublicPolicySyncCallbackRouteImport.update({
    id: '/api/public/policy-sync-callback',
    path: '/api/public/policy-sync-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuditCallbackRoute = ApiPublicAuditCallbackRouteImport.update({
  id: '/api/public/audit-callback',
  path: '/api/public/audit-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApolicesIdEndossosNumRoute = ApolicesIdEndossosNumRouteImport.update({
  id: '/endossos/$num',
  path: '/endossos/$num',
  getParentRoute: () => ApolicesIdRoute,
} as any)
const ApiPublicHooksPolicySyncRoute =
  ApiPublicHooksPolicySyncRouteImport.update({
    id: '/api/public/hooks/policy-sync',
    path: '/api/public/hooks/policy-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/endossos': typeof EndossosRoute
  '/ferramentas': typeof FerramentasRoute
  '/intelligence': typeof IntelligenceRoute
  '/operacao': typeof OperacaoRoute
  '/apolices/$id': typeof ApolicesIdRouteWithChildren
  '/apolices/': typeof ApolicesIndexRoute
  '/api/public/audit-callback': typeof ApiPublicAuditCallbackRoute
  '/api/public/policy-sync-callback': typeof ApiPublicPolicySyncCallbackRoute
  '/api/public/hooks/policy-sync': typeof ApiPublicHooksPolicySyncRoute
  '/apolices/$id/endossos/$num': typeof ApolicesIdEndossosNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/endossos': typeof EndossosRoute
  '/ferramentas': typeof FerramentasRoute
  '/intelligence': typeof IntelligenceRoute
  '/operacao': typeof OperacaoRoute
  '/apolices/$id': typeof ApolicesIdRouteWithChildren
  '/apolices': typeof ApolicesIndexRoute
  '/api/public/audit-callback': typeof ApiPublicAuditCallbackRoute
  '/api/public/policy-sync-callback': typeof ApiPublicPolicySyncCallbackRoute
  '/api/public/hooks/policy-sync': typeof ApiPublicHooksPolicySyncRoute
  '/apolices/$id/endossos/$num': typeof ApolicesIdEndossosNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analytics': typeof AnalyticsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/endossos': typeof EndossosRoute
  '/ferramentas': typeof FerramentasRoute
  '/intelligence': typeof IntelligenceRoute
  '/operacao': typeof OperacaoRoute
  '/apolices/$id': typeof ApolicesIdRouteWithChildren
  '/apolices/': typeof ApolicesIndexRoute
  '/api/public/audit-callback': typeof ApiPublicAuditCallbackRoute
  '/api/public/policy-sync-callback': typeof ApiPublicPolicySyncCallbackRoute
  '/api/public/hooks/policy-sync': typeof ApiPublicHooksPolicySyncRoute
  '/apolices/$id/endossos/$num': typeof ApolicesIdEndossosNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/analytics'
    | '/configuracoes'
    | '/endossos'
    | '/ferramentas'
    | '/intelligence'
    | '/operacao'
    | '/apolices/$id'
    | '/apolices/'
    | '/api/public/audit-callback'
    | '/api/public/policy-sync-callback'
    | '/api/public/hooks/policy-sync'
    | '/apolices/$id/endossos/$num'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/analytics'
    | '/configuracoes'
    | '/endossos'
    | '/ferramentas'
    | '/intelligence'
    | '/operacao'
    | '/apolices/$id'
    | '/apolices'
    | '/api/public/audit-callback'
    | '/api/public/policy-sync-callback'
    | '/api/public/hooks/policy-sync'
    | '/apolices/$id/endossos/$num'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/analytics'
    | '/configuracoes'
    | '/endossos'
    | '/ferramentas'
    | '/intelligence'
    | '/operacao'
    | '/apolices/$id'
    | '/apolices/'
    | '/api/public/audit-callback'
    | '/api/public/policy-sync-callback'
    | '/api/public/hooks/policy-sync'
    | '/apolices/$id/endossos/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EndossosRoute: typeof EndossosRoute
  FerramentasRoute: typeof FerramentasRoute
  IntelligenceRoute: typeof IntelligenceRoute
  OperacaoRoute: typeof OperacaoRoute
  ApolicesIdRoute: typeof ApolicesIdRouteWithChildren
  ApolicesIndexRoute: typeof ApolicesIndexRoute
  ApiPublicAuditCallbackRoute: typeof ApiPublicAuditCallbackRoute
  ApiPublicPolicySyncCallbackRoute: typeof ApiPublicPolicySyncCallbackRoute
  ApiPublicHooksPolicySyncRoute: typeof ApiPublicHooksPolicySyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endossos': {
      id: '/endossos'
      path: '/endossos'
      fullPath: '/endossos'
      preLoaderRoute: typeof EndossosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apolices/': {
      id: '/apolices/'
      path: '/apolices'
      fullPath: '/apolices/'
      preLoaderRoute: typeof ApolicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apolices/$id': {
      id: '/apolices/$id'
      path: '/apolices/$id'
      fullPath: '/apolices/$id'
      preLoaderRoute: typeof ApolicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/policy-sync-callback': {
      id: '/api/public/policy-sync-callback'
      path: '/api/public/policy-sync-callback'
      fullPath: '/api/public/policy-sync-callback'
      preLoaderRoute: typeof ApiPublicPolicySyncCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit-callback': {
      id: '/api/public/audit-callback'
      path: '/api/public/audit-callback'
      fullPath: '/api/public/audit-callback'
      preLoaderRoute: typeof ApiPublicAuditCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apolices/$id/endossos/$num': {
      id: '/apolices/$id/endossos/$num'
      path: '/endossos/$num'
      fullPath: '/apolices/$id/endossos/$num'
      preLoaderRoute: typeof ApolicesIdEndossosNumRouteImport
      parentRoute: typeof ApolicesIdRoute
    }
    '/api/public/hooks/policy-sync': {
      id: '/api/public/hooks/policy-sync'
      path: '/api/public/hooks/policy-sync'
      fullPath: '/api/public/hooks/policy-sync'
      preLoaderRoute: typeof ApiPublicHooksPolicySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApolicesIdRouteChildren {
  ApolicesIdEndossosNumRoute: typeof ApolicesIdEndossosNumRoute
}

const ApolicesIdRouteChildren: ApolicesIdRouteChildren = {
  ApolicesIdEndossosNumRoute: ApolicesIdEndossosNumRoute,
}

const ApolicesIdRouteWithChildren = ApolicesIdRoute._addFileChildren(
  ApolicesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EndossosRoute: EndossosRoute,
  FerramentasRoute: FerramentasRoute,
  IntelligenceRoute: IntelligenceRoute,
  OperacaoRoute: OperacaoRoute,
  ApolicesIdRoute: ApolicesIdRouteWithChildren,
  ApolicesIndexRoute: ApolicesIndexRoute,
  ApiPublicAuditCallbackRoute: ApiPublicAuditCallbackRoute,
  ApiPublicPolicySyncCallbackRoute: ApiPublicPolicySyncCallbackRoute,
  ApiPublicHooksPolicySyncRoute: ApiPublicHooksPolicySyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
